# Generated by Django 4.2.4 on 2023-08-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('responsibilities', models.TextField()),
                ('level', models.CharField(choices=[('jr', 'Junior'), ('mid', 'Mid'), ('sr', 'Senior')], max_length=3)),
                ('skills', models.ManyToManyField(related_name='jobs', to='jobs.skill')),
            ],
        ),
    ]
